=== rudyberton92/Time_Out_Pizzerie_per_asporto/data/commenti.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
elementFormDefault="qualified">

	<xs:element name="commenti">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded">
				<xs:element name="commento">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="ID" type="xs:int"/>
							<xs:element name="utente" type="xs:string"/>
							<xs:element name="testo" type="xs:string"/>
							<xs:element name="sede" type="xs:string"/>
							<xs:element name="data" type="xs:dateTime"/>
						</xs:sequence>	
					</xs:complexType>
				</xs:element>
			</xs:sequence>	
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== rudyberton92/Time_Out_Pizzerie_per_asporto/data/commenti.xml
<?xml version="1.0" encoding="latin1"?>
<?xml-stylesheet type="text/xsl" href="../public_html/commenti.xsl"?>
<commenti xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.commenti.com commenti.xsd">

	<commento>
		<ID>1</ID>
		<utente>rberton</utente>
		<testo>La pizza Ã¨ favolosa, peccato che siano sempre in ritardo con i tempi di consegna!</testo>
		<sede>Torreglia</sede>
		<data>2015-06-27T02:05:00</data>
	</commento>
	
	<commento>
		<ID>2</ID>
		<utente>mroetta</utente>
		<testo>Oridinate 3 pizze Patatosa, ora voglio anche la quarta!</testo>
		<sede>Torreglia</sede>
		<data>2015-06-28T20:05:00</data>
	</commento>
	
	<commento>
		<ID>3</ID>
		<utente>mrubin</utente>
		<testo>I fritti sono senza saleeee!!!</testo>
		<sede>Torreglia</sede>
		<data>2015-06-28T21:36:00</data>
	</commento>
	

	<commento>
		<ID>4</ID>
		<utente>lrossi</utente>
		<testo>Le pizze sono tanto gustose quanto lo sono i pizzaioli!!</testo>
		<sede>Abano Terme</sede>
		<data>2015-09-08T00:00:40</data>
	</commento>
</commenti>
